// WARNING: DO NOT EDIT. This file is automatically generated by AWS CDK.
// Any changes you make will be overwritten on the next deployment.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_project_name": "SkeletonApp",
  "aws_project_stage": "dev",
  "aws_cognito_identity_pool_id": "",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_JLChBIKf9",
  "aws_user_pools_web_client_id": "10kqfavo1hhcekofcthd5i0jip",
  "oauth": {},
  "aws_cognito_username_attributes": ["email"],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": ["email"],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": ["SMS"],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": ["email"],
  "aws_appsync_graphqlEndpoint": "https://ollqwjol3jflje2uxm6k56uo3y.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_appsync_apiKey": "",
  "aws_appsync_realTimeEndpoint": "wss://ollqwjol3jflje2uxm6k56uo3y.appsync-realtime-api.us-east-1.amazonaws.com/graphql",
  "aws_admin_api_endpoint": "https://0w5r3riwf6.execute-api.us-east-1.amazonaws.com/prod/",
  "models": [
    {
      "name": "GeoData",
      "hasSubscriptions": false,
      "hasRateLimit": true
    },
    {
      "name": "Post",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "User",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "Comment",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "Setting",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "Log",
      "hasSubscriptions": true,
      "hasRateLimit": false
    }
  ],
  "generated_at": "2025-08-24T21:43:50.000Z",
  "api_id": "tjcbbj3w4vfetnxz7ajd7ocsly"
};

export default awsmobile;
