// WARNING: DO NOT EDIT. This file is automatically generated by AWS CDK.
// Any changes you make will be overwritten on the next deployment.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_project_name": "SkeletonApp",
  "aws_project_stage": "dev",
  "aws_cognito_identity_pool_id": "",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_XCouXJ8pB",
  "aws_user_pools_web_client_id": "2d8pn8jtucc9t9ck95u0uel9hj",
  "oauth": {},
  "aws_cognito_username_attributes": ["email"],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": ["email"],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": ["SMS"],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": ["email"],
  "aws_appsync_graphqlEndpoint": "https://5pveqvk66bas3jpryd3kj4lnrq.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_appsync_apiKey": "",
  "aws_appsync_realTimeEndpoint": "wss://5pveqvk66bas3jpryd3kj4lnrq.appsync-realtime-api.us-east-1.amazonaws.com/graphql",
  "aws_admin_api_endpoint": "https://0qq0ws1pl7.execute-api.us-east-1.amazonaws.com/prod/",
  "models": [
    {
      "name": "GeoData",
      "hasSubscriptions": false,
      "hasRateLimit": true
    },
    {
      "name": "Post",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "User",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "Setting",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "Log",
      "hasSubscriptions": true,
      "hasRateLimit": false
    }
  ],
  "generated_at": "2025-08-17T03:18:10.000Z",
  "api_id": "n7twxltkxzehtkhm7gygjrh5je"
};

export default awsmobile;
