import 'zone.js';  // Import Zone.js first
import { bootstrapApplication } from '@angular/platform-browser';
import { Amplify } from 'aws-amplify';

import { AppComponent } from './app/app.component';
import { appConfig } from './app/app.config';

// Import AWS configuration (generated by CDK)
async function initializeApp() {
  let awsExports;
  try {
    awsExports = (await import('./aws-exports.js')).default;
    console.log('Using generated AWS configuration');
  } catch {
    console.warn('Generated AWS configuration not found, using fallback configuration');
    // Fallback configuration for local development using Amplify v6 format
    awsExports = {
      Auth: {
        Cognito: {
          userPoolId: 'us-east-1_XXXXXXXXX',
          userPoolClientId: 'xxxxxxxxxxxxxxxxxxxxxxxxxx',
          signUpVerificationMethod: 'code' as const,
          loginWith: {
            email: true,
            username: false,
            phone: false
          },
          passwordFormat: {
            minLength: 8,
            requireLowercase: false,
            requireUppercase: false,
            requireNumbers: false,
            requireSpecialCharacters: false
          }
        }
      },
      API: {
        GraphQL: {
          endpoint: 'https://xxxxxxxxxxxxxxxxxxxxxxxxxx.appsync-api.us-east-1.amazonaws.com/graphql',
          region: 'us-east-1',
          defaultAuthMode: 'userPool' as const
        }
      }
    };
  }

  // Configure Amplify with generated configuration
  Amplify.configure(awsExports);

  // Bootstrap the Angular application with proper config
  bootstrapApplication(AppComponent, appConfig)
    .catch(err => console.error(err));
}

// Initialize the application
initializeApp();
