/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS CDK.
// Any changes you make will be overwritten on the next deployment.

const awsmobile = {
  "aws_project_region": "us-east-1",
  "aws_project_name": "SkeletonApp",
  "aws_project_stage": "dev-v2",
  "aws_cognito_identity_pool_id": "",
  "aws_cognito_region": "us-east-1",
  "aws_user_pools_id": "us-east-1_KpX5Jkuog",
  "aws_user_pools_web_client_id": "21d11r3olffdegfur08ndqekhr",
  "oauth": {},
  "aws_cognito_username_attributes": ["email"],
  "aws_cognito_social_providers": [],
  "aws_cognito_signup_attributes": ["email"],
  "aws_cognito_mfa_configuration": "OFF",
  "aws_cognito_mfa_types": ["SMS"],
  "aws_cognito_password_protection_settings": {
    "passwordPolicyMinLength": 8,
    "passwordPolicyCharacters": []
  },
  "aws_cognito_verification_mechanisms": ["email"],
  "aws_appsync_graphqlEndpoint": "https://pdovgbq2lzclxefvfgclcnjula.appsync-api.us-east-1.amazonaws.com/graphql",
  "aws_appsync_region": "us-east-1",
  "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
  "aws_appsync_apiKey": "",
  "aws_appsync_realTimeEndpoint": "wss://pdovgbq2lzclxefvfgclcnjula.appsync-realtime-api.us-east-1.amazonaws.com/graphql",
  "models": [
    {
      "name": "GeoData",
      "hasSubscriptions": false,
      "hasRateLimit": true
    },
    {
      "name": "Post",
      "hasSubscriptions": true,
      "hasRateLimit": false
    },
    {
      "name": "User",
      "hasSubscriptions": true,
      "hasRateLimit": false
    }
  ],
  "generated_at": "2025-07-26T22:45:52.000Z",
  "api_id": "fqetc6ejxzbzrb5nj6ua64iday"
};

export default awsmobile;
