// AWS Configuration - Generated by CDK deployment
const awsExports = {
  aws_project_region: 'us-east-1',
  aws_cognito_region: 'us-east-1',
  aws_user_pools_id: 'us-east-1_example',
  aws_user_pools_web_client_id: 'example-client-id',
  aws_appsync_graphqlEndpoint: 'https://example.appsync-api.us-east-1.amazonaws.com/graphql',
  aws_appsync_region: 'us-east-1',
  aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS'
};

export default awsExports;
